import { SuperVirtualListConfig, DataItem } from "./types";
export declare function SuperVirtual(config: SuperVirtualListConfig): SuperVirtualList;
declare class SuperVirtualList {
    el: HTMLElement;
    content: HTMLElement | null;
    config: SuperVirtualListConfig;
    data: DataItem[];
    colWidth: number;
    colHeights: number[];
    totalHeight: number;
    activeMap: Map<number, HTMLElement>;
    domPool: Map<number, HTMLElement>;
    viewportHeight: number;
    _ticking: boolean;
    _pendingObservers: HTMLElement[];
    _observerTimer: any;
    MAX_DOM_POOL_SIZE: number;
    resizeObserver: ResizeObserver;
    _debouncedRecalculate: () => void;
    isUpdate: boolean;
    _onScrollThrottled: () => void;
    constructor(config: SuperVirtualListConfig);
    _initData(config: SuperVirtualListConfig): Promise<void>;
    _init_el(): void;
    _init(): Promise<void>;
    updateData(data: any[]): Promise<void>;
    _measure(el: any): Promise<number>;
    _setElementStyle(el: HTMLElement, { x, y, width }: any): void;
    _onScroll(): void;
    isScrollBottom(): Promise<void>;
}
export {};
