name: Sync to Gitee

on:
  push:
    branches:
      - main   # 你实际使用的主分支（如 master）

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mirror to Gitee
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # 设置 Gitee 仓库地址（带上 token）
          git remote add gitee https://${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO }}.git
          
          # 推送代码到 Gitee
          git push --mirror gitee
